PROD:
  adapter:  oracle_enhanced
  database: 192.168.231.128/orcl
  username: tantan
  password: oracle
BTS:
  adapter:  oracle_enhanced
  database: 192.168.231.128/orcl
  username: tantan
  password: oracle